### ISSUE TITLE
Launch an app?

### ISSUE THREAD

**Issue by Bubbalax** [ollo69/ha-samsungtv-smart#109]
Is there a guide on how to launch an app from a dashboard? 

A guide or reference would be helpful.

Thank you, great job with the integration!

**Comment by mendoncart** [comment]
Try run this service:

```
service: media_player.play_media
data:
  media_content_id: 3201907018807
  media_content_type: app
target:
  entity_id: media_player.YOUR_TV
```

Substitute the content_id for the app id.
Here's a list: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications

**Comment by Mazori01** [comment]
> Try run this service:
> 
> ```
> service: media_player.play_media
> data:
>   media_content_id: 3201907018807
>   media_content_type: app
> target:
>   entity_id: media_player.YOUR_TV
> ```
> 
> Substitute the content_id for the app id. Here's a list: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications

Where do I find all App IDs, because the list, doesn't have all app i have installed. Do I have to use the ID or is there a way to only type the app name, for example: media_content_id: Netflix? Is it possible to go to the ambient mode?

**Comment by antonio1475** [comment]
@mendoncart that works, thank you.
@Mazori01 what I do is copy the app name from the mini media player card. For example, on my TV these are some apps IDs:
- YouTube: 9Ur5IzDKqV.TizenYouTube
- Netflix: org.tizen.netflix-app
- Prime Video: org.tizen.primevideo
- Plex: kIciSQlYEM.plex
- Apple TV: com.samsung.tv.aria-video

**Comment by antonio1475** [comment]
To add. Note that in recent HA versions, the default structure won't work from the front-end (it does from Developer Tools)
```
netflix:
  service: media_player.play_media
  data:
    media_content_id: org.tizen.netflix-app
    media_content_type: app
  target:
    entity_id: media_player.samsungtv_smart
```

So you have to edit it like this. change to service_data and remove the target line:
```
netflix:
  service: media_player.play_media
  service_data:
    media_content_id: 3201907018807
    media_content_type: app
    entity_id: media_player.samsungtv_smart
```
