### ISSUE TITLE
Load image from USB input source

### ISSUE THREAD

**Issue by zosocanuck** [ollo69/ha-samsungtv-smart#126]
**Describe the bug**
Unable to switch to USB on a Samsung TV (UN70TU7000BXZA) with Tizen firmware using the following service.  Device is setup with SmartThings.

```
service: media_player.play_media
target:
  entity_id: media_player.xyz
data:
  media_content_type: send_key
  media_content_id: ST_USB
```

**Expected behavior**
Should be able to load an image on a USB stick.

**Environment details:**
 - Home Assistant version installed: 1.19.3
 - Component version installed: 0.4.11
 - TV model: UN70TU7000BXZA

I don't have any configuration options in the configuration.yaml file.  Do I need to?
