### ISSUE TITLE
Control backlight

### ISSUE THREAD

**Issue by LTWood** [ollo69/ha-samsungtv-smart#165]
**Is your feature request related to a problem? Please describe.**
I like to go to sleep with something playing on the TV. I set the volume to a low level and then change the backlight level to its minimum so it's easier to fall asleep.

**Describe the solution you'd like**
Is it possible to send a command that would change the backlight to a specific value, much like the set volume command?

**Describe alternatives you've considered**
My solution right now is to send a combination of key codes to navigate into the settings and change the backlight value by "holding" KEY_LEFT/KEY_RIGHT for ~7 seconds to increase/decrease to maximum/minimum values.

**Comment by solid-pixel** [comment]
I set different brightness for each picture modes, then switch picture mode from HASS.

For instance, I have Standard mode set to 100, and Movie mode set to 20.

Then I call this service to switch picture mode when I want to reduce/increase the brightness:

```yaml
service: samsungtv_smart.select_picture_mode
data:
  entity_id: media_player.YOURTVNAME
  # define your picture mode here
  picture_mode: Movie
```

You can find your TV's picture modes in HASS under Developer Tools > States > `media_player.YOURTVNAME` > Attributes column > `picture_mode_list`
