### ISSUE TITLE
AppList always updating

### ISSUE THREAD

**Issue by rosch100** [ollo69/ha-samsungtv-smart#17]
The Applist is always updating to all available apps. However, I don't want this behaviour. I want the applist to be empty.
My configuration.yaml:

```
samsungtv_smart:
  - host: 192.168.253.40 
    source_list: '{"TV":"KEY_EXIT+2000+KEY_TV+1000+KEY_EXIT", "Ambient":"KEY_AMBIENT+5000+KEY_RETURN", "Denon AVR":"KEY_HDMI+1000+KEY_EXIT"}'
    app_list: '{}'
    load_all_apps: false
    show_channel_number: True

```
By the way, deleting the auto-created applist-192.168.253.40.txt in the samsungtv_smart directory or filling it with an empty applist did not change anything.
The option "load_all_apps" does not change the behavior in any way.
