### ISSUE TITLE
Toggle Intelligent Mode (Adaptive Picture)

### ISSUE THREAD

**Issue by antonio1475** [ollo69/ha-samsungtv-smart#194]
**Is your feature request related to a problem? Please describe.**
[QLED TVs have Intelligent Mode](https://www.samsung.com/us/support/answer/ANS00082443/). Toggling it with the TV Remote takes 12-13 clicks.

**Describe the solution you'd like**
A way to toggle it directly via a command.
This is the info regarding picture_mode when Intelligent Mode is enabled (this is language-dependant!)

```
picture_mode: Adaptive Picture
picture_mode_list: Adaptive Picture
```

Compared to when it's off:
```
picture_mode: Standard
picture_mode_list: Dynamic, FILMMAKER MODE, Movie, Natural, Standard
```

**Describe alternatives you've considered**
Sending the picture_mode: "Adaptive Picture" doesn't work (nor sending Standard to disable Intelligent Mode if it's on)...

So, I'm using a script to toggle it through key pattern. Works, although it obviously goes through all the steps...
```
alias: Toggle Intelligent Mode - Samsung TV
sequence:
  - if:
      - condition: state
        entity_id: media_player.samsungtv_smart
        attribute: picture_mode
        state: Imagen adaptable
    then:
      - service: media_player.play_media
        data:
          media_content_type: send_key
          media_content_id: >-
            KEY_HOME+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_UP+KEY_RIGHT+KEY_RIGHT+KEY_ENTER+KEY_HOME
          entity_id: media_player.samsungtv_smart
    else:
      - service: media_player.play_media
        data:
          media_content_type: send_key
          media_content_id: >-
            KEY_HOME+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_UP+KEY_RIGHT+KEY_RIGHT+KEY_ENTER+KEY_ENTER+KEY_HOME
          entity_id: media_player.samsungtv_smart
mode: single
icon: mdi:television-shimmer

```

**Additional context**
