### ISSUE TITLE
Streaming/Casting camera to TV

### ISSUE THREAD

**Issue by avico78** [ollo69/ha-samsungtv-smart#198]
**Is your feature request related to a problem? Please describe.**
I tried many ways streaming camera to TV but it didn't work 
Samsung Q90

**Describe the solution you'd like**
simple camera streaming to TV
**Describe alternatives you've considered**
I tried every example i could find - nothing worked 

**Additional context**
By the integrations description - it suppose to work but i couldn't manage to run it ,
````
  - service: camera.play_stream
    data:
      media_player: media_player.salon_tv
      format: hls
    target:
      entity_id: camera.front_door
```
