### ISSUE TITLE
TV state is regularly changing, even without any actions

### ISSUE THREAD

**Issue by tadeusz-niemiec** [ollo69/ha-samsungtv-smart#23]
**Describe the bug**
I have NU8042 and I found some weird stuff going on with the state of my TV.
My logs show that every ~25 mins the TV's state changes to "on" and after around 30s back to the "off" state. It happens without any human action, for example during the night.

(Figured this out when I had set an automation to turn off my main light after the TV is turned on - my light was randomly switching off during the day without touching the TV :D)

**Expected behavior**
TV state should change only when I actually turn on/off my TV.

**Screenshots**
![image](https://user-images.githubusercontent.com/42116014/82997845-343f4b80-a007-11ea-96fd-712e57e69632.png)

**Environment details:**
 - Rasbian, Home Assistant as a standalone
 - Home Assistant version installed: 0.109.1
 - Component version installed: v0.3.2 (was happening also before)
 - Last know working version: none
 - TV model: NU8042

**Output of HA logs**
Check the screen above

**My config**
```
samsungtv_smart:
  -  host: 192.168.0.105
     update_method: ping
     source_list: '{"ENTER": "KEY_ENTER", "TV": "KEY_TV", "HDMI": "KEY_HDMI1" }'
```
