### ISSUE TITLE
Using your method of casting video from Youtube doesn't work

### ISSUE THREAD

**Issue by Opontios** [ollo69/ha-samsungtv-smart#256]
Following your instructions regarding casting from Youtube:
```
service: media_player.play_media
data:
  media_content_type: url
  media_content_id: https://youtu.be/fXKTV1fJnTo
  enqueue: play
target:
  entity_id: media_player.samsung_tv_55_curved
```
but the TV opens the Web browser, despite using the "enqueue" parameter.

TV model:  UE55MU6652
Tizen version:  T-KTMDEUC-1310.1, BT-S
