### ISSUE TITLE
Cast to TV (media_player.play_media) does not work

### ISSUE THREAD

**Issue by lexusburn** [ollo69/ha-samsungtv-smart#263]
**Describe the bug**
I would like to stream cast videos to a 2023 samsung tv.

I've found the best solution to get valid informations regarding content_id and content_type is by creating a automation, select play media as action and select the (switched on) tv as media player. Then it's pssible to select media via click in the media selector dialog.

I've tried different sources, because i thought that's a problem related to the source, but i can't get it working with any source.
I've got no changes on the tv (is still in live tv mode) and no error in HA logs.
Three different sources as examples:
```
service: media_player.play_media
data:
  enqueue: play
  media_content_id: media-source://camera/camera.my_eufy_camera
  media_content_type: application/vnd.apple.mpegurl
target:
  entity_id: media_player.samsung_tv
```

```
service: media_player.play_media
data:
  enqueue: play
  media_content_id: media-source://camera/camera.my_unifi_camera
  media_content_type: application/vnd.apple.mpegurl
target:
  entity_id: media_player.samsung_tv
```

```
service: media_player.play_media
data:
  enqueue: play
  media_content_id: media-source://unifiprotect/5f400f270323f503870003e9:event:64c854e102d70b03e4003377
  media_content_type: video/mp4
target:
  entity_id: media_player.samsung_tv
```

**Expected behavior**
I would expect that the media will be streamed to the samsung tv.

**Screenshots**
--

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Docker
 - Home Assistant version installed: 2023.7.3
 - Component version installed: v0.11.6
 - Last know working version: ?
 - TV model: Samsung S95C

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**
