### ISSUE TITLE
Samsung G8 Monitor - DisplayPort as InputSource?

### ISSUE THREAD

**Issue by AfcaEric** [ollo69/ha-samsungtv-smart#274]
So i have this strange thing. I have a Samsung G8 Monitor. My PC is connected to the mini DisplayPort on the monitor.
Now, from the SmartThings webpage, i'm able to call the "samsungvd.mediaInputSource" command with a value of "PC" and it switches to the DisplayPort source.  Calling the same command ("samsungvd.mediaInputSource") with the value of "Display Port" (mind the space in between) it works as well.

From this integration in HA, i have 2 devices:
1. The one from Samsung Smart TV. This one lists only 2 sources: TV and HDMI
2. The one from SamsungTV Smart. This one only lists my HDMI device (HDMI1, PlayStation 5)

Is there any way i can get it working so i can switch from/to the DisplayPort input?

**Comment by ollo69** [comment]
I suppose that `Samsung Smart TV` is the native integration. This one do not use SmartThings so it just display what is possible via WebSocket (TV/HDMI)
`SamsungTV Smart` (this integration) use SmartThings if you configure token during setup, but I don't know what is `samsungvd.mediaInputSource`. If you can provide more detail (example and syntax of your call, may be with some screenshot) I could take a look to understand if this command can be implemented.

**Anyway I strongly suggest to not have both integration configured, because for sure they interfere with each other.**

**Comment by kaixla** [comment]
Hi @ollo69 I have a smart monitor too. M5 version in my case. I believe the issue is that we cannot link our SmartThings account to this.
I have other Samsung regular TVs at home and are listed and can be selected when introducing the Smartthings API Key, but the monitor isn't listed. 
Therefore if we cannot add the Smartthings integration to the Smart Monitor to control the input source (apart from TV or HDMI).

**Comment by ollo69** [comment]
Hi @kaixla,

clear, but seems that @AfcaEric can control his monitor from SmartThings:

> Now, from the SmartThings webpage, i'm able to call the "samsungvd.mediaInputSource" command with a value of "PC" and it switches to the DisplayPort source

**Comment by kaixla** [comment]
Hi @ollo69 what a fast reply! Thanks.

Yes, I can control the monitor from the SmartThings app in my phone.

But unfortunately I cannot use the functionality in this module as I am unable to link it.

**Comment by kaixla** [comment]
I would love to help, but I am not an IT expert, and have never worked with APIs. I have made a quick search of Postman and the Smartthings API, but unfortunately I understand very little of it.
I have my API token that I could use to test, but I am unable to do what you ask for. If you would like to guide me I would be happy to help.
Thanks!

**Comment by AfcaEric** [comment]
Hi ollo,

Thanks for helping out. I'll try to explain a bit further, but please bear with me since i'm pretty new to Smartthings.
Ok, so the monitor is the Samsung G8 OLED. I've started using the Smartthings CLI to see what i would need and found the following (funny) thing:

With Smartthings CLI i find the following 2 capabilities of interest (omitted the rest that's not interesting in this one):
`Capabilities:
────────────────────────────────────
 6   mediaInputSource
 20  samsungvd.mediaInputSource
────────────────────────────────────`

**For the default "mediaInputSource", it lists the following:**
`─────────────────────────────
 1  setInputSource(mode<enum
      - AM
      - CD
      - FM
      - HDMI
      - HDMI1
      - HDMI2
      - HDMI3
      - HDMI4
      - HDMI5
      - HDMI6
      - digitalTv
      - USB
      - YouTube
      - aux
      - bluetooth
      - digital
      - melon
      - wifi>)
─────────────────────────────`

**For the samsungvd.mediaInputSource (which seems to use the same 'mediaInputSource' command but in a slight different way, it gives me the free option to input something:**
`Commands:
───────────────────────────────
 1  setInputSource(id<string>)
───────────────────────────────

? Enter command 1
? Enter command arguments (id) "PC"`

If i enter "PC" or "Display Port" here, it works fine.

I think it's safe to say that this is just deficiency from the Smartthings API, but the possibility is there.
I hope this made any sense. If not, please feel free to tell me what i could help out with

**Comment by ollo69** [comment]
> Not sure if it would be helpful, but i think i'm able to dump the JSON or XML code that's being run with these commands. So if that could be helpful, please let me know.

Yes, it could help. Please attach it

**Comment by AfcaEric** [comment]
Sure, hopefully this is what you are looking for:

**mediaInputSource:**
```
{
    "id": "mediaInputSource",
    "version": 1,
    "status": "live",
    "name": "Media Input Source",
    "ephemeral": false,
    "attributes": {
        "supportedInputSources": {
            "schema": {
                "type": "object",
                "properties": {
                    "value": {
                        "items": {
                            "title": "MediaSource",
                            "enum": [
                                "AM",
                                "CD",
                                "FM",
                                "HDMI",
                                "HDMI1",
                                "HDMI2",
                                "HDMI3",
                                "HDMI4",
                                "HDMI5",
                                "HDMI6",
                                "digitalTv",
                                "USB",
                                "YouTube",
                                "aux",
                                "bluetooth",
                                "digital",
                                "melon",
                                "wifi"
                            ],
                            "type": "string"
                        },
                        "type": "array"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "value"
                ]
            },
            "enumCommands": []
        },
        "inputSource": {
            "schema": {
                "type": "object",
                "properties": {
                    "value": {
                        "title": "MediaSource",
                        "enum": [
                            "AM",
                            "CD",
                            "FM",
                            "HDMI",
                            "HDMI1",
                            "HDMI2",
                            "HDMI3",
                            "HDMI4",
                            "HDMI5",
                            "HDMI6",
                            "digitalTv",
                            "USB",
                            "YouTube",
                            "aux",
                            "bluetooth",
                            "digital",
                            "melon",
                            "wifi"
                        ],
                        "type": "string"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "value"
                ]
            },
            "setter": "setInputSource",
            "enumCommands": []
        }
    },
    "commands": {
        "setInputSource": {
            "name": "setInputSource",
            "arguments": [
                {
                    "name": "mode",
                    "optional": false,
                    "schema": {
                        "title": "MediaSource",
                        "enum": [
                            "AM",
                            "CD",
                            "FM",
                            "HDMI",
                            "HDMI1",
                            "HDMI2",
                            "HDMI3",
                            "HDMI4",
                            "HDMI5",
                            "HDMI6",
                            "digitalTv",
                            "USB",
                            "YouTube",
                            "aux",
                            "bluetooth",
                            "digital",
                            "melon",
                            "wifi"
                        ],
                        "type": "string"
                    }
                }
            ]
        }
    }
}
```

**samsungvd.mediaInputSource:**
```
{
    "id": "samsungvd.mediaInputSource",
    "version": 1,
    "status": "proposed",
    "name": "Media Input Source",
    "ephemeral": false,
    "attributes": {
        "supportedInputSourcesMap": {
            "schema": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                }
                            }
                        },
                        "required": []
                    }
                },
                "additionalProperties": false,
                "required": []
            },
            "enumCommands": []
        },
        "inputSource": {
            "schema": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "value"
                ]
            },
            "enumCommands": []
        }
    },
    "commands": {
        "setInputSource": {
            "name": "setInputSource",
            "arguments": [
                {
                    "name": "id",
                    "optional": false,
                    "schema": {
                        "type": "string"
                    }
                }
            ]
        }
    }
}
```

**Comment by ollo69** [comment]
Reopen this adding FT label, I just do not have any time to take a look...

**Comment by veeroohre** [comment]
Would be great to get the ability to switch to DP. I'd like to do it, too. My use case is that I'm switching a lot between my PC and my work laptop. Using the remote is pain so I plan to use an Ikea switch to do just that. Unfortunately I cannot do it yet. As @AfcaEric wrote it's possible via the SmartThings website.

**Comment by branislavbudzak** [comment]
I have the same issue but with USB-C port on my Samsung M7 Smart Monitor, where I am connecting my Macbook. So it will be cool to be able to switch inputs. HDMI port where I have my Xbox is working, but USB-C is not for some reason and under attributes it is always showing HDMI1 even if I have USB-C opened.

**Comment by germn** [comment]
Some useful info for those who has OLED G8 and wants to use it with HA:

1) You can use SmartThings API to switch to Display Port:

```curl -X POST 'https://api.smartthings.com/v1/devices/DEVICE_ID/commands' -H 'Authorization: Bearer API_TOKEN' --data '{"commands":[{"component":"main","capability":"samsungvd.mediaInputSource","command":"setInputSource","arguments":["PC"]}]}'```
Get and replace above **DEVICE_ID** from https://api.smartthings.com/v1/devices (you need an auth on smartthings.com) and **API_TOKEN** from https://account.smartthings.com/tokens

2) You can use standard HA Samsung [Smart TV integration](https://www.home-assistant.io/integrations/samsungtv/) and provided **remote** service to switch to USB:

```
service: remote.send_command
target:
  device_id: ID_FOR_REMOTE
data:
  command:
    - KEY_HDMI  # It says HDMI, yes, but it actually switches to USB ¯\_(ツ)_/¯
```
I don't remember where I got **ID_FOR_REMOTE** from :(

Surprisingly, I didn't manage to switch to USB using API despite USB being a valid MediaSource for both mediaInputSource and samsungvd.mediaInputSource.

---

Anyway, it's enough to switch between Display Port / USB. The API call can be wrapped with https://www.home-assistant.io/integrations/rest_command/

My results:

**secrets.yaml**
```
display_uid: jhjghjghjghjghjghjghjghjghj
display_api_url: https://api.smartthings.com/v1/devices/ghjghjhgjhgjhgjghjghj/commands
display_api_auth: "Bearer ghjhgjhgjghjhgjghjghj"
```

**configuration.yaml**
```
rest_command:
  34_odyssey_oled_g8_api:
    url: !secret display_api_url
    method: POST
    headers:
      authorization: !secret display_api_auth
    payload: '{"commands":[{"component":"main","capability":"{{capability}}","command":"{{command}}","arguments":["{{arguments}}"]}]}'
    content_type: "application/json; charset=utf-8"
    verify_ssl: false
```

**scripts I use**

```
  display_to_desktop:
    sequence:
      - service: rest_command.34_odyssey_oled_g8_api
        data:
          capability: "samsungvd.mediaInputSource"
          command: "setInputSource"
          arguments: "PC"
      - service: script.display_remove_popup

  display_to_macbook:
    sequence:
      - service: remote.send_command
        target:
          device_id: !secret display_uid
        data:
          command:
            - KEY_HDMI
      - service: script.display_remove_popup

  display_remove_popup:
    sequence:
      - delay:
          milliseconds: 500
      - service: remote.send_command
        target:
          device_id: !secret display_uid
        data:
          command:
            - KEY_RETURN
````

**Comment by ollo69** [comment]
Based on information collected in this thread I released a new version that support the key code "ST_PC" via SmartThings. Please check a let me know if it works as expected.

**Comment by veeroohre** [comment]
Switch to Display Port does not work for me with "ST_PC". It switches to HDMI1.

**Comment by ollo69** [comment]
Why `Spiele-PC`. This is the name that you assign to the input? Can you just rename it PC and try again from integration?

**Comment by veeroohre** [comment]
Yes, I renamed it.

After renaming to "PC" it still switches to HDMI1 and not DisplayPort.

**Comment by ollo69** [comment]
But after renaming did you try to change the input using `curl` command?

**Comment by ollo69** [comment]
Anyway I released a new version where I rewrite this command to be more generic. 
You can now use, for instance, `ST_VD:Spiele-PC` to activate the input `Spiele-PC`.
In this way this is more generic a is possible to use any input name (of course it must exist on the TV).

Tested my side and it work properly, I wait for yours feed-back.

**Comment by veeroohre** [comment]
I works now, but only if I rename the source to e. g. "Spiele-PC". If it's the default name "PC" it still switches to HDMI1 and not DisplayPort. 

Thank you for your help!

**Comment by rusty6285** [comment]
Thanks folks, I wasnt unable to figure out how to send this via API command, but I can confirm that using a script that sends the command 'ST_VD:PCdp' as a 'Remote: Send Command' to the entity works perfectly! just be sure to rename the displayport input to that first.

I'm hoping the renamed input sticks on this new firmware, I had an issue of it always reverting last time I did this.. fingers crossed

**Comment by simonysck** [comment]
@branislavbudzak, @germn 

I figured out how to switch to USB-C directly on Samsung Odyssey G8 without using 'KEY_HDMI' which actually switches between inputs.
The trick is to send the command 'ST_VD:<name of your USB-C>'
It seems like ST_VD recognized the name you give the inputs instead of the nature of the port.
To change the name , go to Home > Connected Devices (should be on the left) > Sources (and pick the USB-C, then press down) >Edit and type what you want it to call in the Edit Name textbox. In my case, I called it ' Laptop'.

Then in the source list configuration , I wrote
`USB-C: ST_VD:Laptop`
and it switches to USB-C everytime. If I am already on USB-C, the monitor shows that you are on USB-C again on the top

**Comment by ahass-thedev** [comment]
This is what I was able to get to work:

`rest_command:
  set_samsung_input_source:
    url: 'https://api.smartthings.com/v1/devices/{{ device_id }}/commands'
    method: POST
    headers:
      Authorization: 'Bearer YOUR_ACCESS_TOKEN'
      Content-Type: 'application/json'
    payload: >
      {
        "commands": [
          {
            "component": "main",
            "capability": "samsungvd.mediaInputSource",
            "command": "setInputSource",
            "arguments": [
              "Display Port"
            ]
          }
        ]
      }
    content_type: 'application/json'`

You can use 

`curl -X GET https://api.smartthings.com/v1/devices/{deviceId}/components/main/capabilities/samsungvd.mediaInputSource/status \
-H "Authorization: Bearer {accessToken}"`

to get the supportedInputSourcesMap for your device and then use the id value to set the arguments in the call

**Comment by ahass-thedev** [comment]
This is what I was able to get to work in home assistant:

rest_command: set_samsung_input_source: url: 'https://api.smartthings.com/v1/devices/{{ device_id }}/commands' method: POST headers: Authorization: 'Bearer YOUR_ACCESS_TOKEN' Content-Type: 'application/json' payload: > { "commands": [ { "component": "main", "capability": "samsungvd.mediaInputSource", "command": "setInputSource", "arguments": [ "Display Port" ] } ] } content_type: 'application/json'

You can use

curl -X GET https://api.smartthings.com/v1/devices/{deviceId}/components/main/capabilities/samsungvd.mediaInputSource/status \ -H "Authorization: Bearer {accessToken}"

to get the supportedInputSourcesMap for your device and then use the id value to set the arguments in the call

**Comment by ahass-thedev** [comment]
This is what I was able to get to work in home assistant:

`rest_command: set_samsung_input_source: url: 'https://api.smartthings.com/v1/devices/{{ device_id }}/commands' method: POST headers: Authorization: 'Bearer YOUR_ACCESS_TOKEN' Content-Type: 'application/json' payload: > { "commands": [ { "component": "main", "capability": "samsungvd.mediaInputSource", "command": "setInputSource", "arguments": [ "Display Port" ] } ] } content_type: 'application/json'`

You can use

`curl -X GET https://api.smartthings.com/v1/devices/{deviceId}/components/main/capabilities/samsungvd.mediaInputSource/status \ -H "Authorization: Bearer {accessToken}"`

to get the supportedInputSourcesMap for your device and then use the id value to set the arguments in the call

**Comment by ismakov-dh** [comment]
Turns out that samsung uses some weird name for USB-C input by default. I realised that after many hours spent sniffing and digging Smart Things requests. Also in my case the tv resets the USB-C input source name to the default value after power off. 
So if anyone has problem switching to the USB-C port, try logging into the Smart Things web UI with browser developer tools opened. Find WebSocket connection in network tab of developer tools and expand `api/cloud/status` event. It will have an array of attributes describing active input source. Here you will find the name that you should use as `setInputSource` command argument.
<img width="795" alt="Screenshot 2024-09-07 at 05 15 40" src="https://github.com/user-attachments/assets/d2f60a08-035d-439f-955c-9c619b562859">

Perhaps this is also applicable to the Display Port input source

**Comment by Sheugel** [comment]
Hi,
Can you elaborate how you got the name to be used to trigger the USB-C source? I don't see these attributes in Chrome developer mode. Thanks

**Comment by ismakov-dh** [comment]
> Hi, Can you elaborate how you got the name to be used to trigger the USB-C source? I don't see these attributes in Chrome developer tools. Thanks

Hi👋
Open dev tools and navigate to the smart things website, do all steps (logging in, etc.) until you see the page with the list of your devices with power switch buttons. Then in the network tab of dev tools choose WebSocket connections filter, there you should see single connection. Fall into it to see messages and search for large incoming message, there will be the name

**Comment by Sheugel** [comment]
Thanks, I got it working!

**Comment by Repareman** [comment]
I apologize for resurrecting this conversation; but you all seem to be very knowledgeable on this front.

I am attempting to get this working with my G9 (G95SC). I am able to send an action through HA developer tools with a "Media Player: Select Source" action to the G9 instance with the source "HDMI"; and that will correclty switch to HDMI.

I have tried all the listed above names. I've tried renaming my Display port source, I've tried to query the web-site with the CURL command. I've tried "PC", "ST_VD:PC", etc. etc. etc. I've had no luck other than HDMI working. I'd really love to be able to get Display Port functioning.

I was not able to view the developer tools network call that was discussed prior. I saw a web-socket command, but it didn't have the list of devices shown there. The map of input sources listed on the smartthings website and in the CURL response say that both "HDMI1" and "Display Port" name is "PC". But using PC doesn't work for switching either input source.

Any assistance, would be greatly appreciated. Sorry again if this isn't the right place.

**Comment by catapultcase** [comment]
Not sure if this is necessary or will fix, but I feel like I also had issue getting it to respond to ST_VD:PC. It was only once I renamed the DP input to something custom on the monitor, that it would accept the command using the custom name, e.g. ST_VD:PCdp

**Comment by Repareman** [comment]
Ah, didn't realize people were sending through the remote. I tried again through the remote. No such luck. "KEY_HDMI" works just fine, but getting it to switch to DisplayPort is starting to feel like an impossible dream.

This may also be a difference between models, you're seems to be the G8, mine is the G9 (G95SC). Only has an HDMI, Micro HDMI, and DisplayPort, and so they seemed to have forgotten and/or ignored 2/3 of the devices inputs. :P

**Comment by Repareman** [comment]
Yeah, sadly that doesn't work either. :(

I've tried going through SmartThings website. I've tried going through the "Media Player: Select Input" action with "Display Port" and through the "Remote: Send command" with "Display Port" and neither work. I've made the curl command with my device and I receive the response that asserts that this should be correct, but it just doesn't want to accept the command it seems. See below the response that I get for the CURL command that was posted earlier in this chat:

`{"supportedInputSourcesMap":{"value":[{"id":"HDMI1","name":"PC"},{"id":"Display Port","name":"PC"}],"timestamp":"2025-01-16T00:47:04.354Z"},"inputSource":{"value":"Display Port","timestamp":"2025-01-16T01:37:55.922Z"}}curl: (3) URL rejected: Bad hostname`

Have also been living inside of the SmartThings web page in the advanced user section trying to get any information, and it's pretty useless as well.

The following are listed in the device settings of SmartThings:

- mediaInputSource.inputSource = ''
- mediaInputSource.supportedInputSources = '[]'
- samsungvd.mediaInputSource.inputSource = 'Display Port'  (<- currently active)
- samsungvd.mediaInputSource.supportedInputSourcesMap = `[{"id":"HDMI1","name":"PC"},{"id":"Display Port","name":"DPort"}]` (note: "DPort" was an attempt at a custom name. Have tried with this in the command as well with no luck)

I've also confirmed that using 'HDMI1' like the ID in the last map doesn't work with any commands either, it has to be 'HDMI' when using the select source on a "Media Player" entity in HA, or "KEY_HDMI" when sending through a remote.

I've also tried running a command through SmartThings for selecting the input "setInputSource". This doesn't list "DisplayPort" as an option, I have tried every option in the drop down and the only one that functions is "HDMI".

I haven't tried sending REST requests yet, maybe that will be my next attempt to try and get something working.

**Comment by Repareman** [comment]
The REST command with "Display Port" works! :D While I am very happy about that, Samsung.... c'mon.....c'mon.... seriously.

@catapultcase  and @ahass-thedev, thank you both so much for your assistance! Is greatly appreciated!

**Comment by edbgon** [comment]
I'm really confused, based on what was written here I thought that I had everything working. I even made an esphome based button that toggles between USB-C and DP. It worked for a day and then suddenly stopped.

I created two sources:
`USB-C: KEY_HDMI+5000+KEY_RETURN
DP: ST_VD:Display Port+3000+KEY_RETURN`

The display port option still shows up when I request the available sources via API. And making a post to the v1 REST api works correctly as well. Not sure why it would suddenly quit.

Here's the API POST via curl if anyone wants to have a go:

`
curl -X POST "https://api.smartthings.com/v1/devices/<device goes here>/commands" \
    -H "Authorization: Bearer <token goes here>" \
    -H "Content-Type: application/json" \
    -d '{"commands":[{"component":"main","capability":"samsungvd.mediaInputSource","command":"setInputSource","arguments":["Display Port"]}]}'
`

**Comment by joe-sydney** [comment]
My USB-C custom name resets when I plug and unplug the source (a laptop), so using ST_VD:xxxx didn't work well (unless I renamed the source all the time).

So I turned to this method, and found out the name given to the USB-C input is "Unknown"! And when I use "Unknown" as the input source, ie: "Laptop: ST_VD:Unknown" ... it works!

The smart monitor knows Unknown after all.

 
> Turns out that samsung uses some weird name for USB-C input by default. I realised that after many hours spent sniffing and digging Smart Things requests. Also in my case the tv resets the USB-C input source name to the default value after power off. So if anyone has problem switching to the USB-C port, try logging into the Smart Things web UI with browser developer tools opened. Find WebSocket connection in network tab of developer tools and expand `api/cloud/status` event. It will have an array of attributes describing active input source. Here you will find the name that you should use as `setInputSource` command argument. <img alt="Screenshot 2024-09-07 at 05 15 40" width="795" src="https://private-user-images.githubusercontent.com/68383839/365334643-d2f60a08-035d-439f-955c-9c619b562859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkzMjg1MzEsIm5iZiI6MTczOTMyODIzMSwicGF0aCI6Ii82ODM4MzgzOS8zNjUzMzQ2NDMtZDJmNjBhMDgtMDM1ZC00MzlmLTk1NWMtOWM2MTliNTYyODU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjEyVDAyNDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiODZmMzcyNjQ5ZjY4NmY2MmYyNTk5OWZhZmE3NDhiZjQ4N2U2ZWJhZjlhYWJjNGZjNDQ0NTRkNDYyYzU5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hEZ52utv6HjtWN4kRkpSD9XXq4aAwgfSTlKKvD6ikNY">
> 
> Perhaps this is also applicable to the Display Port input source

**Comment by danyrd92** [comment]
After the latest updates to the integration, is it possible to change the input source to DisplayPort?

How can this be done nowadays?

**Comment by ahass-thedev** [comment]
The integration is too finicky for me. Not sure if it’s Samsung or the use of websockets on the backend of the integration either way, 

https://github.com/ollo69/ha-samsungtv-smart/issues/274#issuecomment-2274868234

https://github.com/ollo69/ha-samsungtv-smart/issues/274#issuecomment-2596339053

Will never not work due to it being a 1:1 implementation of how Samsung Smarthings backend does it. Give it a shot, should work and give you access to so much more. I use this everyday and have never had an issue once. There are also ways to turn on and off the monitor etc. I essentially reverse engineered the basics of Smarthings into my home assistant.

**Comment by EricSnijders** [comment]
For anyone wondering, I just learned about this great solution/workaround: [ha_smartthing_extra](https://github.com/mik-laj/ha_smartthing_extra). It leverages the official Smartthings integration so no worries about tokens etc. After installing, reloading, and adding it as an integration, you can call the following action:
```
action: smartthing_extra.send_command
data:
  component: main
  device_id: <YOUR_DEVICE_ID_HERE>
  capability: SAMSUNG_VD_MEDIA_INPUT_SOURCE
  command: SET_INPUT_SOURCE
  arguments:
    - Display Port
```

**Comment by jimmyhawkin** [comment]
EricSnijders! You are my Hero! I been going nuts that i cant switch between port in a easy manner. Ty for helping me with this using 

SHARING IS CARING!

action: smartthing_extra.send_command
data:
  component: main
  device_id: <YOUR_DEVICE_ID_HERE>
  capability: SAMSUNG_VD_MEDIA_INPUT_SOURCE
  command: SET_INPUT_SOURCE
  arguments:
    - Display Port

**Comment by jimmyhawkin** [comment]
Is there anyway to use this funktion as a script so i could use it to switch between my HDMI and desplayport on homeassistant? 
Ive tried to make it work but it just wont accept the commando. 

Only works in the developer tool.

**Comment by EricSnijders** [comment]
> Is there anyway to use this funktion as a script so i could use it to switch between my HDMI and desplayport on homeassistant? Ive tried to make it work but it just wont accept the commando.
> 
> Only works in the developer tool.

Hi jimmy,

So here is what I did:

1. Setup the "official" SmartThings integration in HA
2. Add https://github.com/mik-laj/ha_smartthing_extra
3. I've created 2 buttons in my HA dashboard to allow me to quickly switch between inputs (in my case, USB-C and DisplayPort). 2 Buttons look like this:

<img width="468" height="162" alt="Image" src="https://github.com/user-attachments/assets/074df0ba-8d65-478d-a113-c28f50e6de2d" />

```
  - type: horizontal-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: perform-action
          perform_action: smartthing_extra.send_command
          data:
            device_id: <YOUR_SMARTTHINGS_DEVICE_ID_HERE>
            component: main
            capability: SAMSUNG_VD_MEDIA_INPUT_SOURCE
            command: SET_INPUT_SOURCE
            arguments:
              - Display Port
        name: PC
        icon: mdi:monitor
        show_state: false
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: perform-action
          perform_action: smartthing_extra.send_command
          data:
            device_id: <YOUR_SMARTTHINGS_DEVICE_ID_HERE>
            component: main
            capability: SAMSUNG_VD_MEDIA_INPUT_SOURCE
            command: SET_INPUT_SOURCE
            arguments:
              - USB-C
        name: Laptop
        icon: mdi:laptop
        show_state: false
```

**Comment by jimmyhawkin** [comment]
I made abitt of change to make things work as so that if i klick if changes scource from Displayport to hdmi and if i klick again it changes back from hdmi to displyport. And if screen powers down it powers upp the screen then changes. For example this can be good if HDMI has no scource on and i wanna change back to the other source again. and the why buttons im using with conditions that hides one if the other is active. 

Automasation so trigger on button
```
- alias: Toggle monitor boolean after input change
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: smartthing_extra
        service: send_command
  condition:
    - condition: template
      value_template: >
        {{ trigger.event.data.service_data.device_id == '<YOUR_SMARTTHINGS_DEVICE_ID_HERE>' }}
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.monitor_is_displayport
- alias: Wake monitor via media_player
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: smartthing_extra
        service: send_command
  condition:
    - condition: template
      value_template: >
        {{ trigger.event.data.service_data.device_id == '<YOUR_SMARTTHINGS_DEVICE_ID_HERE>'
           and trigger.event.data.service_data.command == 'SET_INPUT_SOURCE' }}
  action:
    - service: media_player.turn_on
      target:
        entity_id: media_player.pc_skarm
```

Button 1 


```
type: conditional
conditions:
  - entity: input_boolean.monitor_is_displayport
    state: "off"
card:
  type: custom:mushroom-template-card
  primary: Skärm Input
  secondary: HDMI → DisplayPort
  icon: mdi:monitor
  tap_action:
    action: perform-action
    perform_action: smartthing_extra.send_command
    data:
      device_id: <YOUR_SMARTTHINGS_DEVICE_ID_HERE>
      component: main
      capability: SAMSUNG_VD_MEDIA_INPUT_SOURCE
      command: SET_INPUT_SOURCE
      arguments: Display Port
  hold_action:
    action: call-service
    service: input_boolean.turn_on
    target:
      entity_id: input_boolean.monitor_is_displayport

```


Button 2


```
type: conditional
conditions:
  - entity: input_boolean.monitor_is_displayport
    state: "on"
card:
  type: custom:mushroom-template-card
  primary: Skärm Input
  secondary: DisplayPort → HDMI
  icon: mdi:monitor
  tap_action:
    action: perform-action
    perform_action: smartthing_extra.send_command
    data:
      device_id: <YOUR_SMARTTHINGS_DEVICE_ID_HERE>
      component: main
      capability: SAMSUNG_VD_MEDIA_INPUT_SOURCE
      command: SET_INPUT_SOURCE
      arguments: HDMI
  hold_action:
    action: call-service
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.monitor_is_displayport

```
