### ISSUE TITLE
Wont switch to app

### ISSUE THREAD

**Issue by callmebackdraft** [ollo69/ha-samsungtv-smart#288]
**Describe the bug**
if i use the regular media player card for this integration i can switch to apps that i have populated in the sources/app list
however i am building my own remote card, which is basically just a grouping of buttons.

all navigational buttons work however with the "direct to app" buttons i created as follows:
```
show_name: false
show_icon: true
type: button
tap_action:
  action: call-service
  service: media_player.select_source
  target:
    entity_id: media_player.tv_woonkamer
  data:
    source: '3201907018807'
entity: media_player.tv_woonkamer
hold_action:
  action: none
icon: phu:netflix
```

nothing happens even though i used the same source id as are used within the app list

**Expected behavior**
swap source to identified app

**Screenshots**
![image](https://github.com/ollo69/ha-samsungtv-smart/assets/14372954/f7ff203e-4cb8-4baa-9be5-a370c3351e07)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO, Raspberry PI 4
 - Home Assistant version installed: Home Assistant OS 11.2 / Home Assistant Core 2023.11.3
 - Component version installed: 0.13.1
 - Last know working version: never worked for me
 - TV model: GQ75Q90TGTXZG

**Output of HA logs**

**Additional context**
