### ISSUE TITLE
Open youtube on a specific video

### ISSUE THREAD

**Issue by SodaSurfer** [ollo69/ha-samsungtv-smart#317]
Hi there
is it possible to open youtube on a specific video when I provide a video id?
currently I can only open youtube app on its' home screen, and I want to be able and open it on a specific video page.

thanks

**Comment by LakeHouse47025** [comment]
Would love to figure this out as well.

**Comment by alexbrasetvik** [comment]
Try…

```
service: media_player.play_media
target:
  entity_id: media_player.frame85
data:
  media_content_id: https://www.youtube.com/watch?v=dQw4w9WgXcQ
  media_content_type: url
  enqueue: "play"
```

`media_content_type: url`, not video, and also needs the `enqueue` option.
