### ISSUE TITLE
TV Control not working UN82MU8000

### ISSUE THREAD

**Issue by codylv7** [ollo69/ha-samsungtv-smart#44]
Hi,

I was able to pair my TV successfully (UN82MU8000), but when I try to control it (Power On/Off, etc.) nothing happens.  I've tried removing integration and devices from TV and repairing, but no luck.  I do not see anything in the log file, but I'll set to debug and see if there are any clues there.

Thanks,
Cody

**Comment by codylv7** [comment]
Nothing in logs when I attempt to turn TV on/off

**Comment by ollo69** [comment]
Did you enable debug? You should add this lines in `configuration.yaml` and than restart HA

```
logger:
  default: info
  logs:
    custom_components.samsungtv_smart: debug
```
