### ISSUE TITLE
Integration doesn't show up on the new integrations button

### ISSUE THREAD

**Issue by Gitarcitano** [ollo69/ha-samsungtv-smart#50]
**Describe the bug**
I've trying to install this component on 0.118.5, but the integration is not showing up on new integrations options like described in the readme:

```
From the Home Assistant front-end, navigate to 'Configuration' then 'Integrations'. Click + button in bottom right corner, search 'SamsungTV Smart', and click 'Configure'.
```

I can't find `SamsungTV Smart`, and I already have rebooted.

**Expected behavior**
To see the integration 

**Screenshots**
![image](https://user-images.githubusercontent.com/44866256/102024928-9416fd00-3d73-11eb-9229-67907dcd7a45.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 0.108.5
 - Component version installed:  v0.3.15
 - Last know working version:
 - TV model: 55TU8000

**Aditional Info**

Already tried to insert it directly on `configuration.yaml` but none media_player entity was created

```yaml
samsungtv_smart:
  - host: 192.168.100.xxx
    name: Samsung Series 8
    api_key: XXXXXXXX-xxxx-xxxx-xxxx-XXXXXXXXXXXX
```
