### ISSUE TITLE
State on and state off inverted

### ISSUE THREAD

**Issue by pilot1981** [ollo69/ha-samsungtv-smart#82]
HASSIO 2021.5.3 on raspberry 3+

Tv Samsung frame 2020

When I send power on command: it go in art mode

when I send power off command: it go in ON state.

regards

**Comment by pilot1981** [comment]
why I don't see art mode state in samsung smartthings hub web portal?


![image](https://user-images.githubusercontent.com/46350465/121039443-5f7b7f80-c7b1-11eb-9678-4c31f57a600c.png)

**Comment by ollo69** [comment]
You should activate debug log for integration and attach here log file, so that I can analyze what happen.

**Comment by pilot1981** [comment]
[log_samsung.txt](https://github.com/ollo69/ha-samsungtv-smart/files/6610420/log_samsung.txt)

**Comment by ollo69** [comment]
What enviroment / hardware are u using? What version of python? I see in your log OSError when sending the command, that is very strange.

**Comment by pilot1981** [comment]
raspberry pi 3+ with HASSIO core-2021.6.2 python 3.8.10

what is OSE?

If I use it:

`  - platform: template
    switches:
      tv_art_mode:
        friendly_name: "TV Art Mode"
        value_template: "{{ state_attr('media_player.samsung_the_frame_65_tizen', 'art_mode_status') == 'on' }}"
        turn_on:
          - service: media_player.turn_on
            entity_id: media_player.samsung_the_frame_65_tizen
          - wait_template: "{{ (is_state('media_player.samsung_the_frame_65_tizen', 'on') and state_attr('media_player.samsung_the_frame_65_tizen', 'art_mode_status') == 'off') or (state_attr('media_player.samsung_the_frame_65_tizen', 'media_content_type') == 'video' or state_attr('media_player.samsung_the_frame_65_tizen', 'app_id') == 'TV/HDMI') }}"
            timeout: '00:02:00'
            continue_on_timeout: false
          - delay: '00:00:01'
          - service: media_player.play_media
            data_template:
              entity_id: media_player.samsung_the_frame_65_tizen
              media_content_id: 'KEY_POWER'
              media_content_type: 'send_key'
        turn_off:
          - service: media_player.turn_off
            entity_id: media_player.samsung_the_frame_65_tizen`

when I go to switch on tv_art_mode sometime TV power on with lastest TV channel....

**Comment by ollo69** [comment]
`OSError` is a python exception.
Why you are using a so complex template? Use the services:

- media_player.turn_on
- media_player.turn_off
- samsungtv_smart.set_art_mode

**Comment by pilot1981** [comment]
I’m not able to use these services in  HA switches…

**Comment by pilot1981** [comment]
ok, I will try with this one:

  - platform: template
    switches:
      samsung_tv_power:
        value_template: "{{ is_state('media_player.samsung_tv', 'on') }}"
        turn_on:
          service: media_player.turn_on
          target:
            entity_id: media_player.samsung_tv
        turn_off:
          service: media_player.set_art_mode
          target:
            entity_id: media_player.samsung_tv

**Comment by pilot1981** [comment]
for the OSE error what I have to do?

**Comment by ollo69** [comment]
```
switch:
  - platform: template
    switches:
        samsung_tv_power:
            value_template: "{{ is_state('media_player.samsung_tv', 'on') }}"
            turn_on:
                service: media_player.turn_on
                target:
                    entity_id: media_player.samsung_tv
            turn_off:
                service: samsungtv_smart.set_art_mode
                target:
                    entity_id: media_player.samsung_tv
```

					


> for the OSE error what I have to do?

Nothing for now, test new template
