### ISSUE TITLE
Helper entity for turn on/off TV

### ISSUE THREAD

**Issue by myhomeiot** [ollo69/ha-samsungtv-smart#86]
Many users with TV connected by WiFi experiencing problems with TV on/off (most cases with on). For this cases is it possible to add extra redundant (all will works as before but for on/off the component will also call homeassistant.turn_on/turn_off for this entity) settings of helper entity which will turn on/off TV?

As an example of usage, user can create switch entity which will use Broadlink IR for ON and OFF the TV and specify it as helper entity for component. Sure in this case better if user will use different IR on/off codes and not power toggle code, fortunately many TV support this.

Thanks in advance!

**Edit:** Because extra control usually based on IR, maybe even better to call scripts instead entity like switch, for example:
```
# https://github.com/yahat/broadlink_mini_homeassistant_ir_codes_samsung_tv
script:
  broadlink_samsungtv_off:
    alias: Broadlink SamsungTV Off
    mode: queued
    sequence:
      - service: remote.send_command
        data_template:
          entity_id: remote.broadlinkir_remote
          command: b64:JgBGAJOVEDoQOhA6DxYPFhAVEBUQFRA6ETkROREUERQRFBEUEBUQFREUERQRORE5EBUQFRE5ETkRORE5ERUQFRA6DzsPFhAADQUAAA==
          num_repeats: 3
  broadlink_samsungtv_on:
    alias: Broadlink SamsungTV On
    mode: queued
    sequence:
      - service: remote.send_command
        data_template:
          entity_id: remote.broadlinkir_remote
          command: b64:JgBGAJKVETkRORA6ERQRFBEUERQRFBE5ETkQOhAVEBUQFREUEBUQOhEUERQRORE5EBURFBA6EBUQOhE5EBUQFRA6EDoRFBEADQUAAA==
          num_repeats: 3
```
